10 IF "TEST"="TEST" PRINT "STRING COMPARISON"
20 IF "TEST"="FOO" PRINT "FAIL: STRING COMPARISON"
30 IF "TEST"<>"TEST" PRINT "FAIL: STRING COMPARISON"
40 IF "TEST"<>"FOO" PRINT "STRING COMPARISON NOT EQUAL"
50 PRINT "PASS: STRING COMPARISON"

