10 I=1
20 J=2
30 A$(I)="FIRST"
40 A$(J)="SECOND"
50 PRINT A$(I)
60 PRINT A$(J)
70 IF A$<>"FIRST" PRINT "FAIL: A$(1) INCORRECT": END
80 IF B$<>"SECOND" PRINT "FAIL: A$(2) INCORRECT": END
90 PRINT "PASS: INDEXED VARIABLES WORK"
