10 REM Test string truncation in indexed variables
20 A$(10)="SHOULD TRUNCATE TO 7 CHARS"
30 PRINT A$(10)
40 IF A$(10)="SHOULD " PRINT "PASS: STRING TRUNCATION IN INDEXED VARIABLES": END
50 PRINT "FAIL: STRING TRUNCATION IN INDEXED VARIABLES"
